### ISSUE TITLE
Missing diagonal entries for L

### ISSUE THREAD

**Issue by blegat** [JuliaSmoothOptimizers/LDLFactorizations.jl#10]
In the example below
```julia
julia> using LDLFactorizations
julia> ldl([  2     1     -83/40;
              1    43/20    0
            -83/40  0       5]).L
3×3 SparseArrays.SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [3, 1]  =  -0.415
  [3, 2]  =  0.465116
```
The entries (1, 1), (2, 2) and (3, 3) with value 1 are missing.
If this is by design, it should maybe be stated in the README that we don't have `L * D * L'` but rather `(L+I) * D * (L+I)'`

**Comment by dpo** [comment]
That's right; L is unit lower triangular, so that its diagonal is made of ones and isn't stored. We'll have to update the README.
