### ISSUE TITLE
Improve data structure

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/LDLFactorizations.jl#13]
It would be convenient for the user to call the symbolic and numerical phases explicitly without having to manage the temporary storage.

**Comment by dpo** [comment]
#48

**Comment by mtanneau** [comment]
Related to this: a helpful functionality for Tulip would be to enable updating a factorization after, e.g., modifying the factored matrix diagonal.

```julia
# compute factor, including symbolic analysis
F = ldl(S)

# Modify diagonal of S
# ...

# Re-compute factorization, re-using existing factor
ldl!(F, S)
```

Obviously, the following conditions would have to be met:
* The dimension and sparsity structure of `S` are not modified
* `S` is still quasi-definite after diagonal changes

CHOLMOD offers this possibility with the [`cholesky!`](https://github.com/JuliaLang/julia/blob/6cd329c371c1db3d9876bc337e82e274e50420e8/stdlib/SuiteSparse/src/cholmod.jl#L1312-L1334) and [`ldlt!`](https://github.com/JuliaLang/julia/blob/6cd329c371c1db3d9876bc337e82e274e50420e8/stdlib/SuiteSparse/src/cholmod.jl#L1476-L1498) functions

**Comment by dpo** [comment]
Modifying the diagonal of S is a full-rank update, so I'm really not sure if any previous computation can be reused. Are you talking about CHOLMOD's update/downdate capabilities?

**Comment by mtanneau** [comment]
No, I mean that if the sparsity structure of `S` is not modified, then that of the factors is not either, so the symbolic phase can be skipped and existing memory re-used for the numeric phase.

Basically I would like to be able to do this:
```julia
# Symbolic phase: ordering and memory allocation
F = symbolic_ldl(S)

for iteration in 1:N
    some_update!(S)  # does not change sparsity structure

    ldl!(F, S)  # does not re-do the symbolic phase
end
```

This situation happens when the diagonal of the SQD augmented system is updated at each IPM iteration.
If the normal equations are solved, then the whole matrix is updated, but its sparsity structure remains the same.

**Comment by dpo** [comment]
Like [this](https://github.com/JuliaSmoothOptimizers/LDLFactorizations.jl/blob/master/src/LDLFactorizations.jl#L469)?

**Comment by mtanneau** [comment]
> 
> 
> Like [this](https://github.com/JuliaSmoothOptimizers/LDLFactorizations.jl/blob/master/src/LDLFactorizations.jl#L469)?

Yes! Let me check that #48 works

**Comment by dpo** [comment]
Yes, that looks right. If you supply a `Symmetric` matrix, it's implied that `upper=true`.

**Comment by dpo** [comment]
Closing this issue. Please feel free to open a new issue if there are difficulties.
