### ISSUE TITLE
Support complex-valued matrices?

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/LDLFactorizations.jl#96]
We use an LDL' factorization in Convex.jl to [check for PSD-ness](https://github.com/jump-dev/Convex.jl/pull/457) of real- and complex-valued hermitian matrices.

Being able to use this package with complex values and arbitrary arithmetic would greatly simplify things for us.

**Comment by dpo** [comment]
I've never tested complex systems; they probably fail and I can imagine why. But what other arithmetic have you seen fail? We use this package with other floating-point systems without problems. I've even used it (with minor changes
0 to compute the symbolic factorization of a matrix of strings...

**Comment by mtanneau** [comment]
>But what other arithmetic have you seen fail?

I meant things like `Complex{BigFloat}`, since for `Complex{Float32}` and `Complex{Float64}` we can use SuiteSparse.

We do have exotic test cases for which we end up checking PSD-ness of `Int` or `Rational`-valued matrices, but that's not a big concern since, in general the factorization will not be integer.

**Comment by dpo** [comment]
If A is rational, L and D should be rational because the factorization is square-root free.
